name: Update images

on:
  workflow_dispatch:
  schedule:
    # 1:37am every Sunday
    - cron: "37 1 * * 0"

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - run: |
          # Get stars/tier card
          curl "https://github-readme-stats.vercel.app/api?username=rohan-buechner&hide_title=true&hide_border=true&show_icons=true&include_all_commits=true&count_private=true&line_height=21&theme=dracula" > images/stars-tier.svg
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=rohan-buechner&hide=html,java&hide_title=true&hide_border=true&layout=compact&langs_count=6&theme=dracula" > images/languages.svg
          curl "http://github-readme-streak-stats.herokuapp.com/?user=rohan-buechner&theme=dracula&hide_border=true" > images/streak.svg
          curl "https://stackoverflow-card.vercel.app/?userID=1105314&theme=dracula&showBorder=false" > images/stackoverflow.svg

      # commit, push
      - uses: stefanzweifel/git-auto-commit-action@v4
